### PR TITLE
fixes scroll to top button on project page

### LINKED ISSUE #203: The scroll up button on the projects page is not working

### PR DESCRIPTION
**Pull request by Jbarget**
### What changes have you made?
NB. the only changes are on lines 35, 36, 81 - 85 and 91 everything else is linting

- adds scroll to the projects page itself
- adjusts scroll to top function to use `refs` from react rather than the global `window` (vanilla js)

### Which issue(s) does this PR fix?

Fixes #203

### How to test

- scroll to bottom of projects page
- click up button, should smooth scroll to top

### CODE REVIEW

File: src/components/Projects.tsx [hunk 1]
```diff
@@ -32,6 +32,8 @@ import { Link } from "react-router-dom";
 const Main = styled.main<FlexboxProps & LayoutProps>`
   display: flex;
   height: 100%;
+  overflow: scroll;
+  scroll-behavior: smooth;
```
Comment (sssoja) [inline src/components/Projects.tsx:36]: loving the smooth scroll

**Review by sssoja — APPROVED** [review]
