### PR TITLE
Fixing homepage layout styles and button size

### LINKED ISSUE #127: Fix image sizes on the homepage to be the same width and height

### LINKED ISSUE #131: Reduce the size of the homepage buy button on mobile view

### PR DESCRIPTION
**Pull request by mantagen**
### What changes have you made?

- GlobalStyles
  - I've added `height: 100%` to body and html. This is because on an actual mobile phone, using 100vh leads to undesired scroll, because it uses the pixel height of the device, not the available screen space (which is diminished by the browser url bar etc etc)
  - see https://stackoverflow.com/questions/6654958/make-body-have-100-of-the-browser-height
  - see https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser
- Home.tsx
  - renames some components for clarity
  - fixes heights of text images
    - using `4vw` has the height of a single line. This is because in this case we really don't want the text to become too wide for the screen. By making the height of the text relative to the _width_ of the screen, we pretty much prevent this from happening.
    - if we think the image sizes are slightly off for some viewports, we can adjust this sizing.  
- BuyButton.tsx
  - removes redundant `p` padding attritbute
  - adds breakpoint values for `py` and `px` attributes

### Which issue(s) does this PR fix?

Fixes  #127 
Fixes #131

### Screenshots (if there are design changes)
image
image

### How to test
- Check home page on different viewport sizes

### CODE REVIEW

**Comment by sssoja** [comment]
Looking great! 

Just a little bit of squishage on Safari. There's a `width: 500px;` on the image maybe we could add a `min-width: 500px too`?

Screenshot 2020-09-09 at 13 53 37
Screenshot 2020-09-09 at 13 53 23

**Review by sssoja — COMMENTED** [review]
Looking great! 

Just a little bit of squishage on Safari. There's a `width: 500px;` on the image maybe we could add a `min-width: 500px too`?

Screenshot 2020-09-09 at 13 53 37
Screenshot 2020-09-09 at 13 53 23

**Comment by mantagen** [comment]
Good spot @sssoja, see latest push.
I think it should do the trick.
Basically getting the sizing of the OXYMORE MANIFESTO #1 text is fiddly cause they're image text.
FYI squashing on Safari was because of flex, you need to set align-items or justify-content (depending on if it's direction column/row) -- otherwise it takes up whole width/height
https://stackoverflow.com/questions/57516373/image-stretching-in-flexbox-in-safari

File: src/components/Home.tsx [hunk 1]
```diff
@@ -39,10 +39,14 @@ const ManifestoLink = styled(NavLink)<TypographyProps & FlexboxProps>`
...
-const Img = styled.img<LayoutProps & SpaceProps>`
-  height: 8vw;
-  align-self: flex-start;
-  ${layout};
+const DoubleLineTextImage = styled.img`
+  height: 10vw;
+  max-height: 88px;
+`;
+const SingleLineTextImage = styled.img<SpaceProps>`
+  height: 5vw;
```
Comment (sssoja) [inline src/components/Home.tsx:47]: logic, logic. I like it

**Review by sssoja — APPROVED** [review]

File: src/components/Home.tsx [hunk 2]
```diff
@@ -32,42 +32,65 @@ const Flex = styled.div<FlexboxProps>`
...
 `;
 
-const Img = styled.img<LayoutProps & SpaceProps>`
-  max-width: 30%;
+const ProjectsLink = styled(NavLink)<TypographyProps & FlexboxProps>`
+  ${typography};
+
+  display: flex;
+  align-self: center;
+  align-items: center;
```
Comment (sssoja) [inline src/components/Home.tsx:58]: Approved! with one small change here.

As with the stack overflow solve, let's update `align-items` to `flex-start`. I've just tested it on Safari and it's looking fresssh

**Review by sssoja — APPROVED** [review]

File: src/components/Home.tsx (hunk 2 above)
Comment (mantagen) [reply src/components/Home.tsx:58]: Weird on my safari `center` is working. `flex-start` working too, will change to that! It's definitely a quirky css bug!
