### PR TITLE
fixes padding on advertising page

### LINKED ISSUE #249: Reduce the padding for the Advertising page on mobile
Screenshot 2020-11-24 at 14 59 08

### PR DESCRIPTION
**Pull request by sssoja**
### What changes have you made?
- the padding on the advertising page was a bit intense on mobile so I've reduced it and also added a `justify-content: center` on the outer `Flex` to get the two sides to balance out

### Which issue(s) does this PR fix?

Fixes #249 

### Screenshots (if there are design changes)
Screenshot 2020-11-24 at 15 44 47

### How to test
check http://localhost:3000/advertising and make sure the padding looks natural on mobile

### CODE REVIEW

**Review by mantagen — APPROVED** [review]

File: src/components/Advertising.tsx [hunk 1]
```diff
@@ -35,29 +35,31 @@ const Advertising: React.FC = () => {
     <Flex
       flex="auto"
       flexDirection={["column", "column", "column", "row", "row"]}
+      justifyContent="center"
```
Comment (mantagen) [inline src/components/Advertising.tsx:38]: Is this fine for both `row` and `column` layouts?

**Review by mantagen — APPROVED** [review]

File: src/components/Advertising.tsx (hunk 1 above)
Comment (sssoja) [reply src/components/Advertising.tsx:38]: I just removed the second to last `"row"` actually as this is unnecessary, but yeah it seems to be fine for both
