### PR TITLE
fixes padding on all pages #111

### LINKED ISSUE #111: Header buttons are incorrectly positioned
Eg: "Oxymore" and "Menu"

image

Check across the different pages, it seems to differ

### PR DESCRIPTION
**Pull request by sssoja**
### What changes have you made?

- removed padding props from all components and applied fixed padding of 24px to `GlobalStyle` 

### Which issue(s) does this PR fix?

Fixes #111 

### How to test
move through each of the pages and check in dev tools the padding is `24px`

### CODE REVIEW

File: src/components/NavMenu.tsx [hunk 1]
```diff
@@ -7,15 +7,17 @@ import {
...
   TypographyProps,
   PositionProps,
   GridProps,
+  SpaceProps,
 } from "styled-system";
 import { zIndexes } from "./theme";
 
 const overlayStyles = css`
-  display: flex;
+  display: -webkit-flex;
```
Comment (Jbarget) [inline src/components/NavMenu.tsx:20]: styled components should do browser compatibility for you, was something not working?

**Review by Jbarget — COMMENTED** [review]
nice work, just one thing :)

File: src/components/NavMenu.tsx (hunk 1 above)
Comment (sssoja) [reply src/components/NavMenu.tsx]: oooh my bad this was a change I made on another branch, I was trying to fix #145. fixed
