### PR TITLE
fixes background across the app

### LINKED ISSUE #183: Remove global background styles so that more than one background can be used
Currently this is the global background on all pages:

Screenshot 2020-10-14 at 13 01 30

What we actually want is for this to be the background on _some_ pages but not all. For example, Conscious Shopping...

We need to come up with a way of implementing more than one background while avoiding this:

Screenshot 2020-10-14 at 13 02 51

So that we can use backgrounds like this:

Screenshot 2020-10-20 at 19 41 43

And this:

Screenshot 2020-10-20 at 19 43 40

### PR DESCRIPTION
**Pull request by Jbarget**
### What changes have you made?

- adds Background component which covers all routes and Header
- comments react routes back in

### Which issue(s) does this PR fix?

Fixes #183 

### Screenshots (if there are design changes)
image

image

### How to test

- go to conscious shopping page and should see black background
- go to projects page and should see marbled background

### CODE REVIEW

File: src/GlobalStyle.tsx [hunk 1]
```diff
@@ -1,26 +1,18 @@
...
 import theme from "./components/theme";
-import background from "./components/assets/backgrounds/background.png";
-
 
 const GlobalStyle = createGlobalStyle`
-@font-face{
-  font-family: SangBleu;
-  src: url(SangBleuOGSerif-Light.otf)
-}
-  html {
```
Comment (sssoja) [inline src/GlobalStyle.tsx:11]: So at the moment the `Div` tag of the `Background` component is not taking up 100% of the page

If you move across the site you start to notice the pattern. It's taking up 100% of its outer container which is only the size of its contents. 

Where you've deleted here the `html {
  height: 100%
} `  in the `GlobalStyle` component if you add it back in and then add `height: 100%` to the `Div` styled component like this: 

Screenshot 2020-10-26 at 11 03 58

then that should do the trick

**Review by sssoja — CHANGES_REQUESTED** [review]

**Comment by Jbarget** [comment]
its good to remove the issue number from the PR title otherwise it can get confusing. Also you have it in the commit message and you add it to the PR description
image

File: src/components/Background.tsx [hunk 2]
```diff
@@ -12,6 +12,7 @@ const Div = styled.div<{ background: Background }>`
   }
   background-repeat: repeat-y;
   background-size: cover;
+  height: 100%;
```
Comment (sssoja) [inline src/components/Background.tsx:15]: Swwweet! Approved with one small change.

I just noticed something of my own omission. 

We don't need `height: 100%` here because this overrides the purpose of `background-repeat`. You can see what happens here:

Screenshot 2020-10-26 at 15 21 35

What we actually want is for the background to repeat _sometimes_ so we can get rid of this line.

**Review by sssoja — APPROVED** [review]

File: src/components/Background.tsx (hunk 2 above)
Comment (sssoja) [reply src/components/Background.tsx:15]: actually no ignore that - this doesn't work. I need to look at this again

Comment (sssoja) [reply src/components/Background.tsx:15]: nope, sorry. I've found myself in the dreaded CSS vortex where one thing works but breaks something else. 

can we phone a friend? aka @mantagen

File: src/App.tsx [hunk 3]
```diff
@@ -28,7 +28,8 @@ const AppContent = styled.div`
   display: flex;
   flex-direction: column;
   padding: ${theme.space[6]}px;
-  `;
+  overflow: auto;
```
Comment (sssoja) [inline src/App.tsx:31]: smashed it!

**Review by sssoja — APPROVED** [review]
