### PR TITLE
Fixes projects menu overlay 

### LINKED ISSUE #122: Menu overlay isn´t working on projects page
@mantagen forgot to mention this one - just assigning in case you have time!

note to self. maybe try adding a z-index to the overlay component but make sure it doesn't do anything weird to the rest of the children, especially when viewing in Safari

### PR DESCRIPTION
**Pull request by mantagen**
### What changes have you made?

- adds `zIndexes` to theme.ts
- makes menu dialog `position: fixed;`

### Which issue(s) does this PR fix?

Fixes #122

### Screenshots (if there are design changes)
image

### How to test
- open menu from projects page
  - should function normally

### CODE REVIEW

File: src/components/theme.ts [hunk 1]
```diff
@@ -9,6 +9,12 @@ export type Colors =
       accentPrimary: string;
     };
 
+export const zIndexes = {
```
Comment (sssoja) [inline src/components/theme.ts:12]: siiiick

**Review by sssoja — APPROVED** [review]
